import { FormEvent, useState } from 'react'
import { Mail, MapPin, Phone, Send, CheckCircle2 } from 'lucide-react'
import SectionTitle from '../components/SectionTitle'
import { company } from '../data/company'
import { useSEO } from '../hooks/useSEO'
export default function Contact(){
  useSEO('تماس با آمارد | تحلیلگران آمارد نوین','اطلاعات تماس و فرم درخواست مشاوره تحلیلگران آمارد نوین.')
  const [sent,setSent]=useState(false); const [error,setError]=useState('')
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const name=String(fd.get('name')||'').trim(),phone=String(fd.get('phone')||'').trim(),message=String(fd.get('message')||'').trim();if(name.length<2||phone.length<7||message.length<10){setError('لطفاً نام، شماره تماس و پیام را کامل وارد کنید.');return}setError('');setSent(true);e.currentTarget.reset()}
  return <><section className="page-hero"><div className="container"><SectionTitle badge="تماس با ما" title="شروع یک گفت‌وگوی" highlight="سازنده" description="برای بررسی محصولات و راهکارهای آمارد، از اطلاعات تماس یا فرم زیر استفاده کنید."/></div></section><section className="section-pad compact-top"><div className="container contact-grid"><div className="contact-info"><div className="contact-card"><Phone/><div><span>تلفن</span>{company.phones.map(x=><a key={x} href={`tel:${x}`}>{x}</a>)}</div></div><div className="contact-card"><Mail/><div><span>ایمیل</span><a href={`mailto:${company.email}`}>{company.email}</a></div></div><div className="contact-card"><MapPin/><div><span>آدرس</span><p>{company.address}</p></div></div><div className="map-faux"><MapPin/><strong>ساختمان آمارد — آمل</strong><span>بلوار آزادگان، نبش آزادگان ۱۲</span><div className="map-grid-lines"/></div></div><form className="contact-form" onSubmit={submit}><div><label>نام و نام خانوادگی *</label><input name="name" placeholder="نام شما"/></div><div><label>شماره تماس *</label><input name="phone" inputMode="tel" placeholder="09..."/></div><div><label>ایمیل</label><input name="email" type="email" placeholder="name@example.com"/></div><div><label>شرکت / سازمان</label><input name="company" placeholder="نام سازمان"/></div><div className="full"><label>موضوع</label><select name="subject"><option>مشاوره محصولات شهرسازی</option><option>مشاوره مالی و اداری</option><option>درخواست همکاری</option><option>سایر</option></select></div><div className="full"><label>پیام *</label><textarea name="message" rows={6} placeholder="نیاز یا درخواست خود را توضیح دهید..."/></div>{error&&<p className="form-error">{error}</p>}{sent&&<p className="form-success"><CheckCircle2/> فرم با موفقیت اعتبارسنجی شد. برای ارسال واقعی، endpoint فرم را به بک‌اند یا سرویس ایمیل متصل کنید.</p>}<button className="btn btn-primary full" type="submit">ثبت درخواست <Send size={18}/></button></form></div></section></>}
